on:
  push
name: make test
jobs:
  test:
    name: make test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: make test
        run: make test
        shell: bash
